#数据库配置
#spring.datasource.url=jdbc:mysql://localhost:3306/mybatis
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver

server :
  port : 8081

spring:
  datasource:
    url : jdbc:mysql://localhost:3306/mybatis2
    username : root
    password : root
  application:
    name: service-provider

# mybatis 别名扫描
mybatis:
  type-aliases-package: com.demo.pojo
# mapper.xml文件位置,如果没有映射文件，请注释掉
#  mapper-locations: classpath:mappers/*.xml
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka #,http://127.0.0.1:10087/eureka


